# SOPS Configuration
# This file configures SOPS encryption settings for this repository

# Creation rules - defines how files are encrypted
creation_rules:
  # Development environment encryption
  - path_regex: profiles/dev/.*\.(secrets\.env|secrets\.yaml)$
    pgp: >-
      FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4,
      A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0
    encrypted_regex: ^(data|stringData|password|secret|key|token|credential|api_key|private_key|client_secret)$

  # Production environment encryption
  - path_regex: profiles/prod/.*\.(secrets\.env|secrets\.yaml)$
    pgp: >-
      FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4,
      A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0
    encrypted_regex: ^(data|stringData|password|secret|key|token|credential|api_key|private_key|client_secret)$

# Key groups - allows multiple keys for decryption
# In production, you might use different keys per environment
key_groups:
  - pgp:
      - FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
      - A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0

