---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitrepository-stage
  namespace: stage
spec:
  url: https://github.com/octopilot/secret-manager-controller.git
  ref:
    branch: main
  interval: 5m
  timeout: 20s
  ignore: |
    /*
    !/deployment-configuration/profiles/stage/**
    !/.sops.yaml
  secretRef:
    name: git-credentials
